export enum IBookingType {
  'CALENDAR_TIMESLOTS' = 'CALENDAR-TIMESLOTS',
  'PICKUP' = 'PICKUP',
  'CALENDAR_NO_TIMESLOTS' = 'CALENDAR-NO-TIMESLOTS',
  'NO_CALENDAR_FIXED_END' = 'NO-CALENDAR-FIXED-END',
}
